/**
 * This config was used to get score 4340 on Scenario 3.
 */
export const config4340 = {
  MIN_THRESHOLD: 0.75,
  THRESHOLD_RAMP: 0.3,
  TARGET_RANGE: 5000,
  URGENCY_MODIFIER: 3,
  CORRELATION_BONUS: 0.3,
  NEGATIVE_CORRELATION_BONUS: 0.5,
  NEGATIVE_CORRELATION_THRESHOLD: -0.5,
  MULTI_ATTRIBUTE_BONUS: 0.5,
  RARE_PERSON_BONUS: 0.5,
  MAX_CAPACITY: 1000,
  TOTAL_PEOPLE: 10000,
  CRITICAL_THRESHOLD: 50,
  EARLY_THRESHOLD: 100,
  CRITICAL_IN_LINE_RATIO: 0.75,
  CRITICAL_CAPACITY_RATIO: 0.8,
  GUARENTEED: 10,
}
