/**
 * This score was from right before adding the PID controller and was right on target.
 */
const data = [
  {
    info: {
      natural_progress: 1,
      target_quota_progress: 1,
      actual_quota_progress: 0.9997,
      progress_gap: 0.0003,
      progress_adjustment: 0.0003,
      rate_adjustment: -0.02,
      threshold: 0.4,
      regular_score: 0,
      endgame_score: 0,
      raw_score: 0,
      deflation_factor: 1.5,
      last_score: 0,
      is_endgame: true,
      critical_attrs: 0,
      has_critical: false,
      has_some_critical: false,
      emergency_eligible: false,
      metrics_efficiency: 1,
      metrics_risk: 0.68,
      metrics_balance: true,
      recommendations: [],
    },
    critical: [],
    config: {
      BASE_THRESHOLD: 0.42,
      MIN_THRESHOLD: 0.2,
      MAX_THRESHOLD: 0.8,
      THRESHOLD_RAMP: 0.3,
      TARGET_RATE: 0.25,
      TARGET_RANGE: 4000,
      URGENCY_MODIFIER: 3,
      CORRELATION_BONUS: 0.2,
      NEGATIVE_CORRELATION_BONUS: 0.5,
      NEGATIVE_CORRELATION_THRESHOLD: -0.5,
      MULTI_ATTRIBUTE_BONUS: 1.2,
      RARE_PERSON_BONUS: 0.4,
      MAX_CAPACITY: 1000,
      TOTAL_PEOPLE: 10000,
      CRITICAL_REQUIRED_THRESHOLD: 20,
      CRITICAL_IN_LINE_RATIO: 0.8,
      CRITICAL_CAPACITY_RATIO: 0.9,
      MIN_RAW_SCORES: 1,
      MESSAGE: 'Base Configuration - Balanced Strategy',
      SCENARIO: '2',
    },
    quotas: [],
    admissionRate: 0.19872560732775787,
    admitted: 998,
    rejected: 4024,
    natural_progress: 1,
    target_quota_progress: 1,
    actual_quota_progress: 0.9997,
    progress_gap: 0.0003,
    progress_adjustment: 0.0003,
    rate_adjustment: -0.02,
    threshold: 0.4,
    regular_score: 0,
    endgame_score: 0,
    raw_score: 0,
    deflation_factor: 1.5,
    last_score: 0,
    is_endgame: true,
    critical_attrs: 0,
    has_critical: false,
    has_some_critical: false,
    emergency_eligible: false,
    rate_analysis: {
      currentRate: 0.1987,
      targetRate: 0.25,
      deviation: -0.0513,
      status: 'too_low',
      recommendation:
        'Consider lowering thresholds or increasing score bonuses',
    },
    critical_progress: [],
    spots_left: 2,
    people_left: 4978,
    incomplete_quotas: 0,
    rejection_analysis: {
      current_rejections: 4024,
      target_rejections: 3000,
      rejection_gap: 1024,
      on_track: false,
    },
  },
  {
    info: {
      natural_progress: 1,
      target_quota_progress: 1,
      actual_quota_progress: 0.9997,
      progress_gap: 0.0003,
      progress_adjustment: 0.0003,
      rate_adjustment: -0.02,
      threshold: 0.4,
      regular_score: 0,
      endgame_score: 0,
      raw_score: 0,
      deflation_factor: 1.5,
      last_score: 0,
      is_endgame: true,
      critical_attrs: 0,
      has_critical: false,
      has_some_critical: false,
      emergency_eligible: false,
      metrics_efficiency: 1,
      metrics_risk: 0.68,
      metrics_balance: true,
      recommendations: [],
    },
    critical: [],
    config: {
      BASE_THRESHOLD: 0.42,
      MIN_THRESHOLD: 0.2,
      MAX_THRESHOLD: 0.8,
      THRESHOLD_RAMP: 0.3,
      TARGET_RATE: 0.25,
      TARGET_RANGE: 4000,
      URGENCY_MODIFIER: 3,
      CORRELATION_BONUS: 0.2,
      NEGATIVE_CORRELATION_BONUS: 0.5,
      NEGATIVE_CORRELATION_THRESHOLD: -0.5,
      MULTI_ATTRIBUTE_BONUS: 1.2,
      RARE_PERSON_BONUS: 0.4,
      MAX_CAPACITY: 1000,
      TOTAL_PEOPLE: 10000,
      CRITICAL_REQUIRED_THRESHOLD: 20,
      CRITICAL_IN_LINE_RATIO: 0.8,
      CRITICAL_CAPACITY_RATIO: 0.9,
      MIN_RAW_SCORES: 1,
      MESSAGE: 'Base Configuration - Balanced Strategy',
      SCENARIO: '2',
    },
    quotas: [],
    admissionRate: 0.19888512840931713,
    admitted: 999,
    rejected: 4024,
    natural_progress: 1,
    target_quota_progress: 1,
    actual_quota_progress: 0.9997,
    progress_gap: 0.0003,
    progress_adjustment: 0.0003,
    rate_adjustment: -0.02,
    threshold: 0.4,
    regular_score: 0,
    endgame_score: 0,
    raw_score: 0,
    deflation_factor: 1.5,
    last_score: 0,
    is_endgame: true,
    critical_attrs: 0,
    has_critical: false,
    has_some_critical: false,
    emergency_eligible: false,
    rate_analysis: {
      currentRate: 0.1989,
      targetRate: 0.25,
      deviation: -0.0511,
      status: 'too_low',
      recommendation:
        'Consider lowering thresholds or increasing score bonuses',
    },
    critical_progress: [],
    spots_left: 1,
    people_left: 4977,
    incomplete_quotas: 0,
    rejection_analysis: {
      current_rejections: 4024,
      target_rejections: 3000,
      rejection_gap: 1024,
      on_track: false,
    },
  },
]
